using UnityEngine;
using System.Collections;

public class EasyMenuManagerIgnoreHide : MonoBehaviour {

    // PLACING THIS SCRIPT ON A UNITY GAME OBJECT WILL CAUSE THE EASY MENU MANAGER'S 'HIDE ON CLOSE' FUNCTION TO IGNORE THIS OBJECT.
    // THIS SCRIPT HAS NO FUNCTION IF THE GAME OBJECT IT IS ATTACHED TO DOES NOT HAVE A 'CANVAS RENDERER' COMPONENT.

}
